### ISSUE TITLE
Masqueraded hosts don't appear in the API

### ISSUE THREAD

**Issue by solarkennedy** [Yelp/sensu#1]
We have an internal ticket for this assigned to @keymone, but I figured I would make it public because (believe it or not) there _are_ other people using this fork (or just our patch).

cc @roobert

I know exactly why. The way the API works is that it iterates over _clients_
https://github.com/sensu/sensu/blob/cec0044ca96221709d4bbecf45c6f5f1133214b2/lib/sensu/api.rb#L471

This works for sensu because the clients table is pruned, and guaranteed to be up to date.

I don't have a super solution to this except scan over the _clients_ table and a new _sources_ table?

It's a hack, but I agree this is a serious limitation of this fork.

cc @portertech in case he is curious. This problem would have to be solved upstream too if they ever decided to allow this.

**Comment by roobert** [comment]
Hi Kyle,

I initially tried your suggestion of creating a 'source' entry in redis along with source:client entries to track masqueraded clients separately from normal clients but it quickly became complicated.

I found just adding client entries for the masqueraded hosts to redis seems to work quite well: https://github.com/roobert/sensu/commit/f50ceffb82fc1c3be9ac7b29df06e53af34c83c6

Everything looks good in Uchiwa and the masqueraded host ends up with duplicated keepalive data from it's original source host, too.

**Comment by solarkennedy** [comment]
I don't understand how it would have duplicate data?

Also, does this entry in redis get reaped when the sensu server prunes stale clients?

**Comment by roobert** [comment]
Keepalives are generated for each client in the client list and then published to rabbitmq here: https://github.com/sensu/sensu/blob/master/lib/sensu/server.rb#L573 - The block compares Time.now to the client[:timestamp] value stored in the client data in redis. Every time event data is processed it gets rewritten to redis as client:real_host and client:masquerading_host with an updated timestamp value from which the new keepalive data is calculated and published.

Masquerading clients do get pruned as they are treated like any other client.

I hope this makes sense.

**Comment by solarkennedy** [comment]
I guess we need to solve both problems. 
1. Sensu server should not setup keepalives for masqueraded hosts? (to stop duplicates)
2. Sensu server should not purne masqueraded hosts from the client table? (but that leads to long term stale clients in the client view right?)

**Comment by roobert** [comment]
I'm not sure that either of these things are a problem.

The checks are running on an actual machine so it makes sense that the masquerading host has a keepalive even if the keepalive is the same as the real host. It makes sense to me that the masquerading host behaves in the same way as any other host.

Regarding pruning: I mistakenly confused pruning and stale state determination, apologies. I've done some testing removing and stopping clients and everything seems to work OK. I was under the impression that sensu-server doesn't remove data from Redis and I can't see any relevant calls to @redis.del or equivalent in server.rb. Which pruning would you be referring to?

**Comment by solarkennedy** [comment]
In my use case, I'm sending masqueraded events on an intermittent basis. I don't actually want them to have keepalives and that stuff :( (I think?)

You are right about pruning. I confused it with pruning aggregates. Stale clients are _detected_ and then you get the keepalive timeouts.

But I don't think I want a keepalive timeout for a masqueraded event, again for my use case.

**Comment by roobert** [comment]
I'd be interested to hear your concerns regarding why you'd prefer to remove keepalives for masqueraded clients. When using Nagios (virtual) service hosts to organise checks it's pretty standard to just set the service host IP to 127.0.0.1. The keepalives still get sent to the service hosts but obviously they never actually trigger an alert.

It may be as simple as adding `next if client[:original_source]` under line 575: https://github.com/sensu/sensu/blob/master/lib/sensu/server.rb#L575

I'll do some testing since I'm not sure what effects removing keepalives for a client may have.

**Comment by hashbrowncipher** [comment]
(context: I work with @solarkennedy)

Reading this thread, I'm thinking that the problems we're running into mostly stem from the fact that keepalive checks are special: they are the only ones for which the sensu server determines staleness.  I propose that if we generalize the concept of staleness to all checks, this problem gets easier.

My idea is that individual checks would gain a 'timeout' parameter.  determine_stale_clients would become determine_stale_checks, and would have the same function: the sensu server would periodically iterate over all checks and create check results for any which are over their configured timeout values.

By default, clients would _not_ have a keepalive check associated with them.  For backwards compatibility, messages received over the keepalive queue would automatically set up a keepalive check, with timeout_warn = 120 and timeout_crit = 180.  Thus, behavior for existing clients would remain the same.  For situations where an independent process (i.e. not a Sensu agent) is intermittently sending events (which I believe is @solarkennedy's use case), keepalives would not be set up.  _However_ individual checks could specify their own timeouts, which would make it really easy to monitor that check results are actually being submitted.

This solves the original issue by demoting clients from first class citizens into mere bundles of metadata.  The list of all clients returned from the API would be the set of all clients with at least one check defined on them.  Clients with keepalives would be included because (naturally) they have a keepalive check defined, and all other clients would be included from the moment the first check is defined on them.

Hopefully what I've said makes some amount of sense.  It's a big refactor, but I think it's the "right" architecture.  I think @roobert's suggestion of adding that single line to determine_stale_clients makes a lot of sense.  It would allow us to (basically) define clients that don't have keepalives, which is a nice first step towards the architecture I'm proposing.

**Comment by roobert** [comment]
Hi Josh! Welcome to the fray :)

Are you saying you'd like to send check data directly to sensu-server rather than via sensu-agent or the sensu-agent socket?

You could send check data to a sensu-agents socket running on the sensu server (or anywhere) and at that point you wouldn't need to worry about making what sound like some pretty complicated changes. 

I'm not sure I really understand what benefit such a large overhaul would have considering that from a functional standpoint we get all the benefits of the existing system with only these few minor changes.. perhaps I'm missing something? :)

Meanwhile, I've tested this change and keepalives now no-longer exist for masqueraded clients:
https://github.com/roobert/sensu/commit/6a111cd89f821c53cdc9a4a9b396d4fa8d6b4ad7 - I'm still not sure if removing the keepalive is a good idea since now when a collection of checks fail you'd have to go and check the status of the real hosts keepalive in order to establish if it's the cause of the problem.

Perhaps @portertech could weigh in as he may have thought about solutions to this problem, too?

**Comment by hashbrowncipher** [comment]
@roobert and I had a very [nice chat](https://gist.github.com/hashbrowncipher/5d31b00478a8ab704ed2) in IRC about this.  The next step will be a post on the mailing list.

**Comment by portertech** [comment]
We could add POST /clients and disable keepalives for clients registered w/ the API. We could then apply check "masquerade" to the result "client", before doing validation and processing etc. We would have a real client, w/ real history, that can be interacted w/ as normal.

**Comment by portertech** [comment]
@solarkennedy Thoughts on the "solution" above?

**Comment by solarkennedy** [comment]
@portertech that makes it a tad harder to add new "fake" hosts on the fly. 
Adding the POST endpoint sounds fine, but it seems that the fake host should be setup automatically, just like a real host is automatically created when it starts sending events?

``` ruby
if check[:source] do
  # fake source detected, add it if it doesn't exist already
  create_client_no_keepalives(:source)
  # apply masquerade logic
  ...
```

**Comment by solarkennedy** [comment]
I think @hashbrowncipher said it best when we should treat them all as "sources", it is just sources from the stock sensu client get keepalives? But the sources themselves should be first class citizens.

**Comment by roobert** [comment]
I've started implimenting some of the suggestions by @portertech here: https://github.com/roobert/sensu/compare/sensu:master...master

By no means finished but so far I've:
- moved @solarkennedy's masquerading stuff before the validation code
- created API end point for client creation with JSON validation (is using bad_request!() here ok?)
- added `:no_keepalive` which skips keepalives if set in client data

You can use this to test adding a client:
https://gist.github.com/roobert/585ae4b2a6b04a1e2c67

**Comment by calebhailey** [comment]
@solarkennedy hi there! :wave: 

We're on a mission to get caught up on all outstanding issues for Sensu (including the Sensu documentation and underlying libraries), and in our ongoing triage I came across a link to this issue. I wonder if this can be closed now that support for ["JIT Clients" was introduced in Sensu 0.18 (released in May 2015)](https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0180---2015-05-05) (NOTE: we are now starting to call these ["Proxy Clients"](https://sensuapp.org/docs/latest/clients#proxy-clients)). :smile: 

/cc @portertech

**Comment by solarkennedy** [comment]
@calebhailey Totally!

**Comment by calebhailey** [comment]
\o/
